In [2]:
#if-else
age = 17
if age >=18:
  print('you are an adult')
else:
  print('you are not an adult')

you are not an adult


In [8]:
#multiple conditions if-elif-else
score = int(input('Enter your score: '))
if score >= 90:
  print('Grade A')
elif score >=80 and score < 90:
  print('Grade B')
elif score >= 70 and score < 80:
  print('Grade C')
else:
  print('Grade D')

Enter your score: 40
Grade D


In [11]:
#nested-if-else
science = int(input('enter your score in science:'))
maths = int(input('enter your score in maths:'))
if science > 80:
    if maths > 80:
        print('you are eligible for admission for applied physics')
    else:
        print('you are not eligible for admission for applied physics')
else:
    print('look for some other subject')

enter your score in science:75
enter your score in maths:90
look for some other subject


In [20]:
file = open('thermodynamics.txt', 'r')
content = file.read() # Read entire file
print(content)
file.close()

Hello, world!
This is a new line.
Appending new content.


In [17]:
file = open('thermodynamics.txt', 'w')
file.write('Hello, world!\n')
file.write('This is a new line.')
file = open('thermodynamics.txt', 'r')
content = file.read()
print(content)
file.close()

Hello, world!
This is a new line.


In [19]:
file = open('thermodynamics.txt', 'a')
file.write('\nAppending new content.')
file.close()
file = open('example.txt', 'r')
content = file.read()
print(content)
file.close()


Appending new content.


In [21]:
with open('thermodynamics.txt', 'r') as file:
 content = file.read()
 print(content)

Hello, world!
This is a new line.
Appending new content.


In [22]:
#list, dictionary , tuple , set
my_list = [1, 2, 3, 4, 5]
print(my_list)

[1, 2, 3, 4, 5]


In [23]:
#tuple
my_tuple = (1, 2, 3, 4, 5)
print(my_tuple)

(1, 2, 3, 4, 5)


In [24]:
#dictionary
my_dict = {'name':'john','age':25,'city':'new york'}
print(my_dict)

{'name': 'john', 'age': 25, 'city': 'new york'}


In [25]:
#extract name from dictionary
print(my_dict['name'])

john


In [26]:
#set
my_set = {1, 2, 3, 4, 5}
print(my_set)

{1, 2, 3, 4, 5}


In [27]:
3**2

9

In [31]:
#squares for a list of numbers
numbers = [1, 2, 3, 4, 5]
squares = []
for idx in numbers:
 squares.append(idx ** 2)

In [32]:
print(squares)

[1, 4, 9, 16, 25]


In [33]:
squares = [i ** 2 for i in numbers]
print(squares)

[1, 4, 9, 16, 25]


In [36]:
#advanced comprension - print a list of even squared number
numbers = [1,2,3,4,5,6,7,8,9,10]
squares = [i**2 for i in numbers if i%2==0]
squares

[4, 16, 36, 64, 100]

In [37]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Filter for even numbers using lambda
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))

# Square the even numbers using lambda
squares = list(map(lambda x: x**2, even_numbers))

print(squares)

[4, 16, 36, 64, 100]


In [39]:
squares = [i**2 for i in range(10) if i%2==0]
squares

[0, 4, 16, 36, 64]

In [40]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(matrix)
#flat = [num for row in matrix for num in row]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [41]:
flat = [num for row in matrix for num in row]
print(flat)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [47]:
import numpy as np
array_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
array_1.shape

(3, 3)

In [48]:
#flatten array
flat = array_1.flatten()
print(flat)

[1 2 3 4 5 6 7 8 9]


In [49]:
type(flat)

numpy.ndarray

In [52]:
#dictionary comprehension
numbers = [1, 2, 3, 4]
squared_dict = {}
for num in numbers:
 squared_dict[num] = num ** 2
print(squared_dict)

{1: 1, 2: 4, 3: 9, 4: 16}


In [53]:
#advanced dictionary comprehension
squared_even_dict = {num: num ** 2 for num in range(10) if num % 2 == 0}
print(squared_even_dict)

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}


In [58]:
class Dog:
 def __init__(self, name, breed, color):
  self.name = name
  self.breed = breed
  self.color = color
 def bark(self):
  return f"{self.name} says woof!"
my_dog = Dog('Buddy', 'Golden Retriever','black')
print(my_dog.bark())

Buddy says woof!


In [59]:
my_dog = Dog('Bruno','bulldog','black')
print(my_dog)

In [61]:
#print the name and breed
print(my_dog.name)
print(my_dog.breed)
print(my_dog.color)

Bruno
bulldog
black


In [63]:
class Car:
  def __init__(self, make, model):
    self.make = make
    self.model = model
  def display_info(self):
    return f"Car: {self.make} {self.model}"
car1 = Car('Toyota', 'Camry')
print(car1.display_info())

Car: Toyota Camry


In [64]:
car1.make

'Toyota'

In [65]:
car1.model

'Camry'

In [69]:
class Animal:
  def __init__(self, name):
    self.name = name
class Dog(Animal):
  def speak(self):
    return f"{self.name} says woof!"
my_pet = Dog('Max')
print(my_pet.speak())

Max says woof!


In [70]:
!pip install numpy

In [71]:
!pip install pandas

In [72]:
##numpy stands for numerical python which is used for performing mathematical calculations
import numpy as np
array_1d = np.array([1,2,3,4,5])
print(array_1d)

[1 2 3 4 5]


In [73]:
array_1d.ndim

1

In [74]:
type(array_1d)

numpy.ndarray

In [75]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
array_2d.ndim

2

In [77]:
array_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(array_3d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [78]:
array_3d.ndim

3

In [79]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix)
print('-------------------------')
print(np.linalg.inv(matrix))

[[1 2]
 [3 4]]
-------------------------
[[-2.   1. ]
 [ 1.5 -0.5]]


In [84]:
import pandas as pd
data = pd.read_csv('train.csv')
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [85]:
data.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [87]:
my_dict = {'name':['hari','subrat','karthik','shruti'],
           'age':[20,21,22,23],
           'location':['bangalore','kolkata','delhi','mumbai']}
print(my_dict)

{'name': ['hari', 'subrat', 'karthik', 'shruti'], 'age': [20, 21, 22, 23], 'location': ['bangalore', 'kolkata', 'delhi', 'mumbai']}


In [88]:
df = pd.DataFrame(my_dict)
print(df)

      name  age   location
0     hari   20  bangalore
1   subrat   21    kolkata
2  karthik   22      delhi
3   shruti   23     mumbai


In [89]:
type(df)

pandas.core.frame.DataFrame

In [90]:
my_dict = {'name':['shruti','shrikant','arun','hari']}
df = pd.Series(my_dict)
print(df)

name    [shruti, shrikant, arun, hari]
dtype: object


In [91]:
type(df)

pandas.core.series.Series

In [92]:
df

name    [shruti, shrikant, arun, hari]
dtype: object

In [104]:
import pandas as pd
data = pd.read_csv('train.csv')
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [105]:
data.shape

(891, 12)

In [106]:
#filter for passengers more than 70 years of age
data[data['Age']>70].head()

PassengerId  Survived  Pclass                                  Name  \
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   
493          494         0       1               Artagaveytia, Mr. Ramon   
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
851          852         0       3                   Svensson, Mr. Johan   

      Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
96   male  71.0      0      0  PC 17754  34.6542    A5        C  
116  male  70.5      0      0    370369   7.7500   NaN        Q  
493  male  71.0      0      0  PC 17609  49.5042   NaN        C  
630  male  80.0      0      0     27042  30.0000   A23        S  
851  male  74.0      0      0    347060   7.7750   NaN        S

In [107]:
#mean of column age
a = data['Age'].mean().round(3)
print(a)

29.699


In [108]:
#median of column age
data['Age'].median()

28.0

In [109]:
#null values
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [110]:
#fill the missing values under age column
data_updated = data['Age'].fillna(data['Age'].mean(),inplace=True)

/tmp/ipython-input-3991340397.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_updated = data['Age'].fillna(data['Age'].mean(),inplace=True)


AttributeError: 'NoneType' object has no attribute 'isnull'