<a href="https://colab.research.google.com/github/Ramjeet-Dixit/IITM-AIML-Rdixit/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## KNN

In [1]:
#importing essential modules
from sklearn import datasets
import pandas as pd
import numpy as np

In [51]:
#load iris data from datasets module of sklearn
#iris = datasets.load_iris()
#load wine data from datasets module of sklearn
wine = datasets.load_wine()
print(type(iris))
print(type(wine))

<class 'sklearn.utils._bunch.Bunch'>
<class 'sklearn.utils._bunch.Bunch'>


In [53]:
#extract the keys of iris dictionary
#print(iris.keys())
print(wine.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])


In [54]:
#type(iris.data)
#data represent input data (4 columns)
type(wine.data)
#data represent input data (13 columns)

numpy.ndarray

In [55]:
#iris.data
#iris.target
wine.data
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [56]:
#iris.feature_names
wine.feature_names


['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [57]:
#iris.target
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [58]:
#iris.target_names
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [59]:
#type(iris.target)
type(wine.target)

numpy.ndarray

In [61]:
#iris.DESCR
wine.DESCR

'.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 178\n:Number of Attributes: 13 numeric, predictive attributes and the class\n:Attribute Information:\n    - Alcohol\n    - Malic acid\n    - Ash\n    - Alcalinity of ash\n    - Magnesium\n    - Total phenols\n    - Flavanoids\n    - Nonflavanoid phenols\n    - Proanthocyanins\n    - Color intensity\n    - Hue\n    - OD280/OD315 of diluted wines\n    - Proline\n    - class:\n        - class_0\n        - class_1\n        - class_2\n\n:Summary Statistics:\n\n============================= ==== ===== ======= =====\n                                Min   Max   Mean     SD\n============================= ==== ===== ======= =====\nAlcohol:                      11.0  14.8    13.0   0.8\nMalic Acid:                   0.74  5.80    2.34  1.12\nAsh:                          1.36  3.23    2.36  0.27\nAlcalinity of Ash:            10.6  30.0    19.5   3.3\nMagnesium:      

In [62]:
#x = iris.data #input array assigned as x
#y = iris.target #output variable assigned as y
x_wine = wine.data
y_wine = wine.target

In [63]:
#split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=123)

In [64]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=8)
#assume k = 8

knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [65]:
y_pred = knn.predict(x_test)
#predict the labels on the test data

In [66]:
y_pred

array([1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 1, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2,
       2, 2, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 1, 2])

In [67]:
y_test
#pre existing or the actual labels

array([1, 2, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2,
       2, 2, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 1, 2])

In [68]:
x_test.shape

(60, 4)

In [69]:
#number (%) of correct predictions; number of labels correctly predicted
knn.score(x_test, y_test)

0.95

In [70]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

[[22  0  0]
 [ 0 16  0]
 [ 0  3 19]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       0.84      1.00      0.91        16
           2       1.00      0.86      0.93        22

    accuracy                           0.95        60
   macro avg       0.95      0.95      0.95        60
weighted avg       0.96      0.95      0.95        60



In [71]:
y_pred_train = knn.predict(x_train)
#predict the labels on the test data

In [72]:
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        28
           1       0.94      0.97      0.96        34
           2       0.96      0.93      0.95        28

    accuracy                           0.97        90
   macro avg       0.97      0.97      0.97        90
weighted avg       0.97      0.97      0.97        90



### Tune and Optimize kNN in Python Using scikit-learn

In [73]:
from sklearn.model_selection import GridSearchCV

parameters = {"n_neighbors": range(1, 50)}

gridsearch = GridSearchCV(KNeighborsClassifier(), parameters, cv=5)

gridsearch.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 50)})

GridSearchCV repeatedly fits kNN classifers on a part of the data and tests the performances on the remaining part of the data.

Doing this repeatedly will yield a reliable estimate of the predictive performance of each of the values for k.

In this example, you test the values from 1 to 50.

In the end, it will retain the best performing value of k, which you can access with .best_params_:

In [74]:
gridsearch.best_params_

{'n_neighbors': 3}

In this code, you print the parameters that have the lowest error score.

With .best_params_, you can see that choosing 3 as value for k will yield the best predictive performance.

Now that you know what the best value of k is, you can see how it affects your train and test performances:

In [75]:
y_pred = gridsearch.predict(x_test)
#n_neighbors=3

In [77]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

[[22  0  0]
 [ 0 15  1]
 [ 0  1 21]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       0.94      0.94      0.94        16
           2       0.95      0.95      0.95        22

    accuracy                           0.97        60
   macro avg       0.96      0.96      0.96        60
weighted avg       0.97      0.97      0.97        60



In [79]:
y_pred_train = gridsearch.predict(x_train)
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        28
           1       0.94      0.97      0.96        34
           2       0.96      0.93      0.95        28

    accuracy                           0.97        90
   macro avg       0.97      0.97      0.97        90
weighted avg       0.97      0.97      0.97        90



**Improvising results using weights hyperparamter**

In [80]:
parameters={'n_neighbors': range(1, 50),
                         'weights': ['uniform', 'distance']}
GD = GridSearchCV(KNeighborsClassifier(),parameters,cv=5)
# default options --> uniform (all points in the neighborhood are weighted equally)
# another option --> distance (weights closer neighbors more heavily than farther neighbors)

In [81]:
GD.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 50),
                         'weights': ['uniform', 'distance']})

In [82]:
GD.best_params_

{'n_neighbors': 6, 'weights': 'distance'}

In [83]:
y_pred = GD.predict(x_test)

In [84]:
print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

[[22  0  0]
 [ 0 15  1]
 [ 0  0 22]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       1.00      0.94      0.97        16
           2       0.96      1.00      0.98        22

    accuracy                           0.98        60
   macro avg       0.99      0.98      0.98        60
weighted avg       0.98      0.98      0.98        60



In [85]:
y_predtrain = GD.predict(x_train)

In [86]:
print(confusion_matrix(y_train, y_predtrain))

print(classification_report(y_train, y_predtrain))

[[28  0  0]
 [ 0 34  0]
 [ 0  0 28]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        28
           1       1.00      1.00      1.00        34
           2       1.00      1.00      1.00        28

    accuracy                           1.00        90
   macro avg       1.00      1.00      1.00        90
weighted avg       1.00      1.00      1.00        90



k = 8, D = U, TA = 95, TRA = 97

K = 3, D = U, TA = 97, TRA = 97

K = 6, D = D, TA = 98, TRA = 100